version: '3'
services:
  servicocontroladorprofessor:
    build: servico-controlador-professor/
    links:
      - servicocadastroprofessor
    ports:
      - "9998:8080"
  servicocadastroprofessor:
    build: servico-cadastro-professor/
    ports:
      - "9997:8080"
  servicefachada:
    build: servico-fachada/
    links:
      - servicocontroladorprofessor
    ports:
      - "9996:8080"
  servicefrontend:
    build: servico-frontend/
    links:
      - servicefachada
    ports:
      - "9995:8080"
